// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAozs-9VVyqYynvyjvVd3gl_d2wj2qJdpA',
    appId: '1:110697411663:web:d5f33ec9d4003e4a0f263a',
    messagingSenderId: '110697411663',
    projectId: 'fir-newswaves',
    authDomain: 'fir-newswaves.firebaseapp.com',
    storageBucket: 'fir-newswaves.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_OHh3iFEM2aJ_T1AjDnNUovMxvbKl8yw',
    appId: '1:110697411663:android:aeedb80fc93b158a0f263a',
    messagingSenderId: '110697411663',
    projectId: 'fir-newswaves',
    storageBucket: 'fir-newswaves.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuL8JOLPn4UaxMOD38MBCtpRWTRj4XRfg',
    appId: '1:110697411663:ios:9cb125bc8683b7b10f263a',
    messagingSenderId: '110697411663',
    projectId: 'fir-newswaves',
    storageBucket: 'fir-newswaves.appspot.com',
    iosBundleId: 'com.example.tubes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuL8JOLPn4UaxMOD38MBCtpRWTRj4XRfg',
    appId: '1:110697411663:ios:2a82a6c19268eea00f263a',
    messagingSenderId: '110697411663',
    projectId: 'fir-newswaves',
    storageBucket: 'fir-newswaves.appspot.com',
    iosBundleId: 'com.example.tubes.RunnerTests',
  );
}
